### ISSUE TITLE
I don't have enough ways to tell you you're awesome

### ISSUE THREAD

**Issue by wondermade** [northlandchurch/Website-Styles#1]
Look at that clean HTML/CSS! The function starting page! The video in the background! Things are working! The only problem is the limits on my abilities to properly tell you we're off to a great start!

**Comment by jhnwlsn** [comment]
@wondermade Ha! Thanks man, really means a ton! It's coming together more quickly than I thought, so hopefully we have time to do some really awesome stuff!
