### ISSUE TITLE
Create guidelines for photography tech specs

### ISSUE THREAD

**Issue by johnbarrierwilson** [northlandchurch/Website-Styles#2]
Need to create a few guidelines for photography specifically addressing photo size, style, etc.

**Comment by jhnwlsn** [comment]
@chadturnbull: I'll get back to creating these actual guidelines soon, but in the meantime, you and Dede should go take a look at a few of these sites when you start selecting/updating photography. These resources are where I'm getting my pictures from, and they are really, _really_ great photos for FREE and totally copyright-free (this is a new trend that's going around). These will be a good place for you to get some great photography.....and you could even tell Becky that this is where she should get her photography! ;)

- [Unsplash](https://unsplash.com/)
- [FindA.Photo](http://finda.photo/)

Need more ministry-focused photography? These aren't free, but generally really great mostly-non-cheesy Christian stock photography:
- [Lightstock](https://www.lightstock.com/)
